FROM node:16.16.0
RUN mkdir -p /src/app
WORKDIR '/src/app'
COPY package.json package.json
COPY package-lock.json package-lock.json
RUN npm install
COPY . /src/app
#EXPOSE 4200
#EXPOSE 8080
EXPOSE 80/tcp
EXPOSE 80/udp
#CMD [ "node", "server.js" ]
CMD ["npm", "start"]
#CMD ["npm", "run", "start"]