name: Deploy to GitHub Pages

on:
  push:
    branches:
      - development  # Ou a branch que você deseja monitorar

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 18.14.0  # Use a versão correta do Node.js

    - name: Install dependencies
      run: cd beeBeer && npm install && npm install -g @angular/cli@latest

    - name: Build Angular app
      run: cd beeBeer && npm run build

    - name: Deploy to GitHub Pages
      run: cd .. && cd beeBeer && npx ngh  # Usando ngh com o diretório de build correto
      env:
        NODE_OPTIONS: '--max-old-space-size=4096'  # Aumenta a alocação de memória para evitar erros de alocação


