name: Deploy to GitHub Pages

on:
  push:
    branches:
      - development  # Ou a branch que você deseja monitorar

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 18.14.0  # Use a versão correta do Node.js

    - name: Install dependencies
      run: cd beeBeer && npm install

    - name: Build Angular app
      run: npm install -g @angular/cli@latest && ng build --watch --configuration development

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist  # Caminho para a pasta de build do Angular
